# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push
  #pull_request:
   # branches: [ "main" ]

  
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: '21'

      # Runs a set of commands using the runners shell
      - name: Build and Test
        working-directory: DevOps-Masterclass/docker/app1-hello/springboot/hello-spring
        run: mvn -B clean verify
       
      - name: create report
        uses: actions/upload-artifact@v4
        with:
            name: test-reports
            path: DevOps-Masterclass/docker/app1-hello/springboot/hello-spring/target/surefire-reports
          
  docker-build-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: '21'

      # Runs a set of commands using the runners shell
      - name: Build jar for docker
        working-directory: DevOps-Masterclass/docker/app1-hello/springboot/hello-spring
        run: mvn clean install
       
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}    
      - name: Build and Push Docker Image 
        uses: docker/build-push-action@v6 
        with:
            context: docker/appl-hello/springboot/hello-spring
            push: true
            tags: |
                ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest